spring.application.name=hexhiveint
server.port=80
server.forward-headers-strategy=framework
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.path=/


# Database Configuration
spring.datasource.url=jdbc:h2:file:./data/greysense_v2;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Better error handling for debugging
server.error.include-message=always

# AWS IoT Core Configuration
aws.iot.endpoint=a156k9xp82njw1-ats.iot.ap-south-1.amazonaws.com
aws.iot.clientId=GreySenseBackend
aws.iot.topic=greysense/sensors
aws.iot.rootCaPath=classpath:certs/AmazonRootCA1.pem
aws.iot.certPath=classpath:certs/certificate.pem.crt
aws.iot.keyPath=classpath:certs/private.pem.key
